export const LOCALES = {
  ru: "Русский",
  en: "English",
  es: "Español",
  de: "Deutsch",
  fr: "Français"
};

const RUSSIAN = {
  appTitle: "Live Voice Translator", session: "Переводчик встречи", history: "История", settings: "Настройки",
  configureOpenAI: "Подключите OpenAI", configure: "Настроить", ready: "Готов", connecting: "Подключение", live: "В эфире", reconnecting: "Восстановление", error: "Ошибка", limit: "Лимит времени",
  you: "Вы", participant: "Собеседник", mode: "Режим работы", translation: "Перевод", notes: "Конспект", both: "Вместе", transcript: "Текст",
  translationHint: "Переводите разговор голосом без сохранения текста.", notesHint: "Запишите разговор и получите структурированный конспект.", bothHint: "Переводите голос и одновременно готовьте конспект.", transcriptHint: "Сохраните полный текст разговора без озвучивания.",
  startTranslation: "Начать перевод", startNotes: "Начать конспект", startMeeting: "Начать встречу", startTranscript: "Начать запись", stop: "Остановить",
  openai: "OpenAI", microphone: "Микрофон", route: "Маршрут", configured: "Настроен", allowed: "Разрешён", required: "Настройте", notRequired: "Не требуется", solo: "Проверка в одиночку", conference: "Конференция",
  soloDescription: "Перевод прозвучит на этом Mac", conferenceDescription: "Голос направляется собеседнику", audioRoute: "Аудиомаршрут", notice: "В режимах с конспектом аудио отправляется в OpenAI. История хранится локально.", understood: "Понятно", fix: "Исправить",
  used: "Использовано {minutes} мин · {sessions} сеансов", apiNotConfigured: "API не настроен", setupCopy: "Добавьте API-ключ, чтобы начать перевод.",
  settingsTitle: "Настройки перевода", keyPrivacy: "Ключ остаётся только на этом устройстве и используется для прямого подключения к OpenAI.", api: "OpenAI API", apiKey: "API-ключ", show: "Показать", hide: "Скрыть", testConnection: "Проверить подключение", testing: "Проверяем…", accessible: "OpenAI доступен", enterKey: "Введите ключ", save: "Сохранить настройки", saved: "Сохранено",
  interfaceLanguage: "Язык интерфейса", youSpeak: "Вы говорите", youHear: "Вы слышите", language: "Язык", participantLanguage: "Язык собеседника", voiceForParticipant: "Голос собеседнику", voiceForYou: "Голос вам", audioOutputs: "Аудиовыходы", outputParticipant: "Перевод для собеседника", outputYou: "Перевод для вас", monitor: "Слышать собственный перевод", notesTitle: "Конспект встречи", detail: "Подробность", saveTranscript: "Сохранять полный текст встречи локально", retention: "Хранить историю", sessionLimit: "Лимит одной сессии",
  historyTitle: "История встреч", deleteAll: "Удалить всю историю", noMeetings: "Конспекты встреч", noMeetingsCopy: "Завершённые встречи появятся здесь.", copy: "Копировать", download: "Скачать Markdown", fullTranscript: "Полный текст", clearConfirm: "Удалить все локальные конспекты и транскрипции?", historyCleared: "История очищена",
  permission: "Нет доступа к микрофону. Разрешите его в настройках Chrome.", keyError: "OpenAI отклонил API-ключ. Проверьте ключ в настройках.", quota: "Достигнут лимит OpenAI API. Проверьте баланс и лимиты проекта.", network: "Соединение прервано. Проверьте интернет и повторите запуск."
};

const TRANSLATIONS = {
  ru: RUSSIAN,
  en: { ...RUSSIAN, session: "Meeting interpreter", history: "History", settings: "Settings", configureOpenAI: "Connect OpenAI", configure: "Set up", ready: "Ready", connecting: "Connecting", live: "Live", reconnecting: "Reconnecting", error: "Error", limit: "Time limit", you: "You", participant: "Participant", mode: "Mode", translation: "Translate", notes: "Notes", both: "Both", transcript: "Text", startTranslation: "Start translation", startNotes: "Start notes", startMeeting: "Start meeting", startTranscript: "Start transcript", stop: "Stop", audioRoute: "Audio route", interfaceLanguage: "Interface language", save: "Save settings", saved: "Saved", historyTitle: "Meeting history", deleteAll: "Delete all history", noMeetings: "Meeting notes", noMeetingsCopy: "Completed meetings will appear here.", copy: "Copy", download: "Download Markdown", fullTranscript: "Full transcript", used: "Used {minutes} min · {sessions} sessions", setupCopy: "Add an API key to start translating.", translationHint: "Translate the conversation aloud without saving text.", notesHint: "Record the conversation and get structured notes.", bothHint: "Translate speech and prepare notes at the same time.", transcriptHint: "Save the full conversation text without speech output.", solo: "Solo test", conference: "Conference", soloDescription: "Translation plays on this Mac", conferenceDescription: "Voice is routed to the participant", openai: "OpenAI", microphone: "Microphone", route: "Route", configured: "Configured", allowed: "Allowed", required: "Set up", notRequired: "Not required", notice: "In note modes, audio is sent to OpenAI. History stays local.", understood: "Got it", fix: "Fix", youSpeak: "You speak", participantLanguage: "Participant speaks", outputParticipant: "To meeting", outputYou: "For you" },
  es: { ...RUSSIAN, session: "Intérprete de reunión", history: "Historial", settings: "Ajustes", configureOpenAI: "Conectar OpenAI", configure: "Configurar", ready: "Listo", connecting: "Conectando", live: "En directo", reconnecting: "Reconectando", error: "Error", limit: "Límite de tiempo", you: "Usted", participant: "Interlocutor", mode: "Modo", translation: "Traducir", notes: "Notas", both: "Ambos", transcript: "Texto", startTranslation: "Iniciar traducción", startNotes: "Iniciar notas", startMeeting: "Iniciar reunión", startTranscript: "Iniciar transcripción", stop: "Detener", audioRoute: "Ruta de audio", interfaceLanguage: "Idioma de la interfaz", save: "Guardar ajustes", saved: "Guardado", historyTitle: "Historial de reuniones", deleteAll: "Eliminar historial", noMeetings: "Notas de reuniones", noMeetingsCopy: "Las reuniones terminadas aparecerán aquí.", copy: "Copiar", download: "Descargar Markdown", fullTranscript: "Transcripción completa", used: "Usado {minutes} min · {sessions} sesiones", setupCopy: "Añada una clave API para empezar a traducir.", translationHint: "Traduce la conversación en voz alta sin guardar texto.", notesHint: "Graba la conversación y prepara notas estructuradas.", bothHint: "Traduce la voz y prepara notas a la vez.", transcriptHint: "Guarda el texto completo sin salida de voz.", youSpeak: "Usted habla", participantLanguage: "El participante habla", outputParticipant: "A la reunión", outputYou: "Para usted", solo: "Prueba individual", conference: "Conferencia", soloDescription: "La traducción suena en este Mac", conferenceDescription: "La voz llega al interlocutor", microphone: "Micrófono", route: "Ruta", configured: "Configurado", allowed: "Permitido", required: "Configurar", notRequired: "No es necesario", notice: "En los modos de notas, el audio se envía a OpenAI. El historial es local.", understood: "Entendido", fix: "Corregir" },
  de: { ...RUSSIAN, session: "Meeting-Dolmetscher", history: "Verlauf", settings: "Einstellungen", configureOpenAI: "OpenAI verbinden", configure: "Einrichten", ready: "Bereit", connecting: "Verbinden", live: "Live", reconnecting: "Neu verbinden", error: "Fehler", limit: "Zeitlimit", you: "Sie", participant: "Gesprächspartner", mode: "Modus", translation: "Übersetzen", notes: "Notizen", both: "Beides", transcript: "Text", startTranslation: "Übersetzung starten", startNotes: "Notizen starten", startMeeting: "Meeting starten", startTranscript: "Transkript starten", stop: "Stoppen", audioRoute: "Audioausgabe", interfaceLanguage: "Sprache der Oberfläche", save: "Einstellungen speichern", saved: "Gespeichert", historyTitle: "Meeting-Verlauf", deleteAll: "Verlauf löschen", noMeetings: "Meeting-Notizen", noMeetingsCopy: "Abgeschlossene Meetings erscheinen hier.", copy: "Kopieren", download: "Markdown laden", fullTranscript: "Vollständiges Transkript", used: "Verwendet {minutes} Min. · {sessions} Sitzungen", setupCopy: "Fügen Sie einen API-Schlüssel hinzu, um zu starten.", translationHint: "Übersetzt das Gespräch laut, ohne Text zu speichern.", notesHint: "Zeichnet das Gespräch auf und erstellt strukturierte Notizen.", bothHint: "Übersetzt Sprache und erstellt gleichzeitig Notizen.", transcriptHint: "Speichert den vollständigen Text ohne Sprachausgabe.", youSpeak: "Sie sprechen", participantLanguage: "Teilnehmer spricht", outputParticipant: "Zum Meeting", outputYou: "Für Sie", solo: "Einzeltest", conference: "Konferenz", soloDescription: "Übersetzung läuft auf diesem Mac", conferenceDescription: "Stimme geht zum Gesprächspartner", microphone: "Mikrofon", route: "Route", configured: "Eingerichtet", allowed: "Erlaubt", required: "Einrichten", notRequired: "Nicht erforderlich", notice: "In Notizmodi wird Audio an OpenAI gesendet. Der Verlauf bleibt lokal.", understood: "Verstanden", fix: "Beheben" },
  fr: { ...RUSSIAN, session: "Interprète de réunion", history: "Historique", settings: "Réglages", configureOpenAI: "Connecter OpenAI", configure: "Configurer", ready: "Prêt", connecting: "Connexion", live: "En direct", reconnecting: "Reconnexion", error: "Erreur", limit: "Limite de temps", you: "Vous", participant: "Interlocuteur", mode: "Mode", translation: "Traduire", notes: "Notes", both: "Les deux", transcript: "Texte", startTranslation: "Démarrer la traduction", startNotes: "Démarrer les notes", startMeeting: "Démarrer la réunion", startTranscript: "Démarrer la transcription", stop: "Arrêter", audioRoute: "Itinéraire audio", interfaceLanguage: "Langue de l’interface", save: "Enregistrer", saved: "Enregistré", historyTitle: "Historique des réunions", deleteAll: "Supprimer l’historique", noMeetings: "Notes de réunion", noMeetingsCopy: "Les réunions terminées apparaîtront ici.", copy: "Copier", download: "Télécharger Markdown", fullTranscript: "Transcription complète", used: "Utilisé {minutes} min · {sessions} séances", setupCopy: "Ajoutez une clé API pour commencer.", translationHint: "Traduit la conversation à voix haute sans enregistrer de texte.", notesHint: "Enregistre la conversation et crée des notes structurées.", bothHint: "Traduit la voix et prépare les notes en même temps.", transcriptHint: "Enregistre le texte complet sans sortie vocale.", youSpeak: "Vous parlez", participantLanguage: "Participant parle", outputParticipant: "Vers la réunion", outputYou: "Pour vous", solo: "Test individuel", conference: "Conférence", soloDescription: "La traduction est jouée sur ce Mac", conferenceDescription: "La voix est envoyée à l’interlocuteur", microphone: "Micro", route: "Acheminement", configured: "Configuré", allowed: "Autorisé", required: "Configurer", notRequired: "Non requis", notice: "En mode notes, l’audio est envoyé à OpenAI. L’historique reste local.", understood: "Compris", fix: "Corriger" }
};

export function t(locale, key, variables = {}) {
  const text = (TRANSLATIONS[locale] || TRANSLATIONS.ru)[key] || RUSSIAN[key] || key;
  return text.replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? "");
}

export function localizePage(locale) {
  document.documentElement.lang = locale;
  document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(locale, element.dataset.i18n); });
  document.querySelectorAll("[data-i18n-title]").forEach((element) => { element.title = t(locale, element.dataset.i18nTitle); });
  document.querySelectorAll("[data-i18n-aria]").forEach((element) => { element.setAttribute("aria-label", t(locale, element.dataset.i18nAria)); });
}
